name:                h2o
version:             0.1.0.1
github:              "yamaton/h2o"
license:             BSD3
author:              "Yamato Matsuoka"
maintainer:          "yamato.matsuoka@tetradresearch.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/yamaton/h2o#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- MissingH
- extra

library:
  source-dirs: src

executables:
  h2oc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - h2o
    - optparse-applicative

tests:
  h2o-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - h2o
    - tasty
    - tasty-hunit
    - hedgehog
    - tasty-hedgehog
    - tasty-expected-failure
    - tasty-golden
    - utf8-string
