name: h2o
version: 0.1.20
github: yamaton/h2o
license: MIT
author: "Yamato Matsuoka"
maintainer: yamato.matsuoka@tetradresearch.com
copyright: "2021 Tetrad Research"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/yamaton/h2o#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - aeson
  - extra
  - text
  - formatting
  - optparse-applicative
  - filepath
  - typed-process
  - ordered-containers

library:
  source-dirs: src

executables:
  h2o:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      # - -eventlog     # for threadscope
      ## ---------------------------------------------------------------------------------------
      ## Require following to build static executable with ghc-musl docker image:
      ## stack build --docker --docker-image "utdemir/ghc-musl:v19-ghc8104" --copy-bins
      ##
      # - -O2
      # - -static
      # - -optl-static  # same as ld-options:  - -static
      # - -optl-pthread #                      - -pthread
      # - -fPIC

    dependencies:
      - h2o

tests:
  h2o-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - h2o
      - tasty
      - tasty-hunit
      - hedgehog
      - tasty-hedgehog
      - tasty-expected-failure
      - tasty-golden
