# Completions for samtools

# subcommands
complete -f -c samtools -n __fish_use_subcommand -a dict -d "create a sequence dictionary file"
complete -f -c samtools -n __fish_use_subcommand -a faidx -d "index/extract FASTA"
complete -f -c samtools -n __fish_use_subcommand -a fqidx -d "index/extract FASTQ"
complete -f -c samtools -n __fish_use_subcommand -a index -d "index alignment"
complete -f -c samtools -n __fish_use_subcommand -a calmd -d "recalculate MD/NM tags and '=' bases"
complete -f -c samtools -n __fish_use_subcommand -a fixmate -d "fix mate information"
complete -f -c samtools -n __fish_use_subcommand -a reheader -d "replace BAM header"
complete -f -c samtools -n __fish_use_subcommand -a targetcut -d "cut fosmid regions (for fosmid pool only)"
complete -f -c samtools -n __fish_use_subcommand -a addreplacerg -d "adds or replaces RG tags"
complete -f -c samtools -n __fish_use_subcommand -a markdup -d "mark duplicates"
complete -f -c samtools -n __fish_use_subcommand -a ampliconclip -d "clip oligos from the end of reads"
complete -f -c samtools -n __fish_use_subcommand -a collate -d "shuffle and group alignments by name"
complete -f -c samtools -n __fish_use_subcommand -a cat -d "concatenate BAMs"
complete -f -c samtools -n __fish_use_subcommand -a merge -d "merge sorted alignments"
complete -f -c samtools -n __fish_use_subcommand -a mpileup -d "multi-way pileup"
complete -f -c samtools -n __fish_use_subcommand -a sort -d "sort alignment file"
complete -f -c samtools -n __fish_use_subcommand -a split -d "splits a file by read group"
complete -f -c samtools -n __fish_use_subcommand -a quickcheck -d "quickly check if SAM/BAM/CRAM file appears intact"
complete -f -c samtools -n __fish_use_subcommand -a fastq -d "converts a BAM to a FASTQ"
complete -f -c samtools -n __fish_use_subcommand -a fasta -d "converts a BAM to a FASTA"
complete -f -c samtools -n __fish_use_subcommand -a bedcov -d "read depth per BED region"
complete -f -c samtools -n __fish_use_subcommand -a coverage -d "alignment depth and percent coverage"
complete -f -c samtools -n __fish_use_subcommand -a depth -d "compute the depth"
complete -f -c samtools -n __fish_use_subcommand -a flagstat -d "simple stats"
complete -f -c samtools -n __fish_use_subcommand -a idxstats -d "BAM index stats"
complete -f -c samtools -n __fish_use_subcommand -a phase -d "phase heterozygotes"
complete -f -c samtools -n __fish_use_subcommand -a stats -d "generate stats (former bamcheck)"
complete -f -c samtools -n __fish_use_subcommand -a ampliconstats -d "generate amplicon specific stats"
complete -f -c samtools -n __fish_use_subcommand -a flags -d "explain BAM flags"
complete -f -c samtools -n __fish_use_subcommand -a tview -d "text alignment viewer"
complete -f -c samtools -n __fish_use_subcommand -a view -d "SAM<->BAM<->CRAM conversion"
complete -f -c samtools -n __fish_use_subcommand -a depad -d "convert padded BAM to unpadded BAM"


# Switches
complete -f -c samtools -n "__fish_seen_subcommand_from dict" -o ai -d "Include archives"