#!/usr/bin/env bash

# Execute H2O executable within bubblewrap if available.

readonly h2opath="$1"
readonly cmd="$2"
BASEDIR="$(dirname "$(readlink -f "$0")")"
readonly BASEDIR

if [[ -x "$(command -v $h2opath)" ]] && [[ -x "$(command -v $cmd)" ]]; then
    if [[ "$(uname -s)" == "Linux" ]] && [[ -x "$(command -v bwrap)" ]]; then
	echo "[info] bwrap!" 1>&2
        bwrap --ro-bind / / --dev /dev --tmpfs /tmp --unshare-all -- "$h2opath" --command "$cmd" --format json
    elif [[ "$(uname -s)" == "Darwin" ]]; then
	echo "[info] sandbox-exec!" 1>&2
        sandbox-exec -f "$BASEDIR"/profile.sb -- "$h2opath" --command "$cmd" --format json
    else
	echo "[warn] no sandbox running!" 1>&2
        "$h2opath" --command "$cmd" --format json
    fi
else
    exit 127
fi
