{-# LANGUAGE DuplicateRecordFields #-}

module GenBashCompletions where

import HelpParser
import Text.Printf

bashTemplate :: String
bashTemplate =
  unlines
    [ "# autogenerated bash script",
      "",
      "_func()",
      "{",
      "    local cur prev words cword",
      "    _init_completion -n = || return",
      "    opts=\"%s\"",
      "",
      "    if [[ ${cur} == -* ]] || (( COMP_CWORD == 1 )); then",
      "        COMPREPLY=( $(compgen -W \"${opts}\" -- \"${cur}\") )",
      "        return 0",
      "    fi",
      "",
      "    COMPREPLY=( $(compgen -W \"${opts}\" -- \"${cur}\") )",
      "    return 0",
      "}",
      "",
      "## -o bashdefault and -o default are fallback",
      "complete -F _func -o bashdefault -o default %s"
    ]

getOptsArray :: [Opt] -> String
getOptsArray opts = unwords $ concatMap (map _raw . _names) opts

indent :: Int -> String -> String
indent n s = replicate n ' ' ++ s

genBashScript :: String -> [Opt] -> String
genBashScript cmd opts = res
  where
    optsArray = getOptsArray opts
    res = printf bashTemplate optsArray cmd
