# autogenerated bash script

_func()
{
    local cur prev words cword
    _init_completion -n = || return
    opts="-k -w -H -I --idx-no-seq -d --alt --alt-drop -f -f --min-occ-floor -g -r -n -m -D -P --dual -X -p -N -G -F -M --hard-mask-level --mask-len --max-chain-skip --max-chain-iter --chain-gap-scale --no-long-join --lj-min-ratio --splice --sr --split-prefix --frag --for-only --rev-only --heap-sort --no-pairing -A -B -O -O -E -E -C -z -z -s -u --end-bonus --score-N --splice-flank --junc-bed --junc-bonus --end-seed-pen --no-end-flt --cap-sw-mem -a -o -Q -L -R -y -c --cs --cs --MD --eqx -Y --seed -t -2 -K --secondary --max-qlen --paf-no-hit --sam-hit-only -x -ub --no-kalloc --print-qname --print-seeds"

    if [[ ${cur} == -* ]] || (( COMP_CWORD == 1 )); then
        COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
        return 0
    fi

    COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
    return 0
}

## -o bashdefault and -o default are fallback
complete -F _func -o bashdefault -o default minimap2
