name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-release:
    name: stack w/ ghc ${{ matrix.ghc }} for ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        stack: ['latest']
        ghc: ['latest']
        build: ['macos']
        include:
          # - build: linux
          #   os: ubuntu-latest
          #   target: x86_64-unknown-linux
          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Haskell Stack
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
          stack-version: ${{ matrix.stack }}

      - name: Make ~/.stack as cache
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack

      - name: Build release binary
        run: |
          stack build --copy-bins

      - name: Archive the binary
        run: |
          mv -f "$(stack path --local-bin)/h2o" .
          tar -czf h2o-${{ matrix.target }}.tar.gz h2o

      - name: Upload the release binary
        uses: actions/upload-artifact@v2
        with:
          name: h2o-${{ matrix.target }}.tar.gz
          path: ./h2o-${{ matrix.target }}.tar.gz
