name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-release:
    name: stack / ghc ${{ matrix.ghc }} for ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        stack: ["latest"]
        ghc: ["latest"]
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux
          - build: linux-arm
            os: ubuntu-latest
            target: arm-unknown-linux-gnueabihf
          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Haskell Stack
        uses: actions/setup-haskell@v1.1.4
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
          stack-version: ${{ matrix.stack }}

      - name: Make ~/.stack as cache
        uses: actions/cache@v2.1.3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack

      - name: Build release binary
        run: |
          stack build --copy-bins

      - name: Move binary to asset dir
        run: |
          mv "${stack path --local-bin}/h2o"  ./h2o-${{ matrix.target }}

      - name: Upload the release binary
        uses: actions/upload-artifact@v2
        with:
          name: h2o-${{ matrix.build }}
          path: ./h2o-${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
